include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	An event notification library
Site=		http://monkey.org/~provos/libevent/
License=	BSD
Title=		Libevent
Name=		libevent
Version=	2.0.11
Revision=	0
URL=		http://monkey.org/~provos/
Source=		$(Name)-$(Version)-stable.tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE

UncompressedName = $(Name)-$(Version)-stable
