include ../../Library/GNU.mk

Title=		Libevent
Name=		libevent
Version=	2.0.21
Revision=	0
URL=		http://github.com/downloads/libevent/libevent/
Source=		$(Name)-$(Version)-stable.tar.gz

LicenseFile=	$(SourceDir)/LICENSE

UncompressedName=$(Name)-$(Version)-stable
