include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		Libevent
Name=		libevent
Version=	2.0.13
Revision=	0
URL=		http://monkey.org/~provos/
Source=		$(Name)-$(Version)-stable.tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE

UncompressedName = $(Name)-$(Version)-stable
