include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		PycURL
Name=		pycurl
Version=	7.19.0
Revision=	1
URL=		http://pycurl.sourceforge.net/download/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING2
