BuildRequires += $(LibDir)/libintl.la # gettext
BuildRequires += $(LibDir)/libntlm.la # libntlm
BuildRequires += $(LibDir)/libidn.la  # libidn

Requires += org.rudix.pkg.libntlm,libntlm,libntlminstall.pkg

include ../../Library/GNU.mk

Title=		GNU SASL
Name=		gsasl
Version=	1.8.0
Site=		$(GnuHome)/$(Name)
Source=		$(GnuMirror)/$(Name)/$(Name)-$(Version).tar.gz
License=	GPL
