BuildRequires += $(LibDir)/libintl.la # static-gettext
BuildRequires += $(LibDir)/libntlm.la # libntlm
BuildRequires += $(LibDir)/libidn.la  # static-libidn

Requires += org.rudix.pkg.libntlm,libntlm,libntlminstall.pkg

include ../../Library/GNU.mk

Title=		GNU SASL
Name=		gsasl
Version=	1.8.0
Revision=	0
URL=		http://ftp.gnu.org/gnu/gsasl/
Source=		$(Name)-$(Version).tar.gz
