include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		Python Twitter Tools
Name=		twitter
Version=	1.7.2
Revision=	0
URL=		http://pypi.python.org/packages/source/t/twitter/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/PKG-INFO
