include ../../Library/GNU.mk

Description=	GCL - an implementation of Common Lisp
Title=		GNU Common Lisp
Name=		gcl
Version=	2.6.12
Site=		$(GnuHome)/$(Name)
Source=		$(GnuMirror)/gcl//$(Name)-$(Version).tar.gz

UncompressedName=gcl
