include ../../Library/GNU.mk

Description=	GCL - an implementation of Common Lisp
Title=		GNU Common Lisp
Name=		gcl
Version=	2.6.12
Revision=	0
Site=		http://www.gnu.org/software/gcl/
URL=		http://ftp.gnu.org/gnu/gcl/
Source=		$(Name)-$(Version).tar.gz

UncompressedName=gcl
