include ../../Library/Configure.mk

Title=		Zlib
Name=		zlib
Version=	1.2.12
Site=		https://www.zlib.net
Source=		https://zlib.net/$(Name)-$(Version).tar.gz
License=	zlib License

LicenseFile=	LICENSE
