include ../../Library/Python.mk

Title=		PyLZMA
Name=		pylzma
Version=	0.4.9
Site=		https://www.joachim-bauch.de/projects/pylzma/
Source=		https://github.com/fancycode/pylzma/archive/v$(Version).tar.gz
License=	LGPLv2

ReadMeFile=	$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/LICENSE
