include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Description=	pip installs packages. Python packages. An easy_install replacement
Site=		http://pypi.python.org/pypi/pip
License=	Python
Title=		pip
Name=		pip
Version=	1.0.1
Revision=	0
URL=		http://pypi.python.org/packages/source/p/pip/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/docs/index.txt
LicenseFile=	$(SourceDir)/license.txt
