--- Makefile.orig	2011-05-28 18:37:04.000000000 -0300
+++ Makefile	2011-05-28 18:37:38.000000000 -0300
@@ -1,6 +1,6 @@
 INSTALL_DIR=/usr/local/bin
-MAN_DIR=/usr/local/man/man1
-ETC_DIR=/etc
+MAN_DIR=/usr/local/share/man/man1
+ETC_DIR=/usr/local/etc
 VERSION=1.0.9
 DIST_FILES=COPYING INSTALL Makefile README \
 	colordiff.pl colordiffrc colordiffrc-lightbg cdiff.sh BUGS TODO CHANGES colordiff.1 \
@@ -28,17 +28,16 @@
 	if [ ! -f ${DESTDIR}${INSTALL_DIR}/cdiff ] ; then \
 	  install cdiff.sh ${DESTDIR}${INSTALL_DIR}/cdiff; \
 	fi
-	install -Dm 644 colordiff.1 ${DESTDIR}${MAN_DIR}/colordiff.1
-	install -Dm 644 cdiff.1 ${DESTDIR}${MAN_DIR}/cdiff.1
+	install -d ${DESTDIR}${MAN_DIR}
+	install -m 644 colordiff.1 ${DESTDIR}${MAN_DIR}/colordiff.1
+	install -m 644 cdiff.1 ${DESTDIR}${MAN_DIR}/cdiff.1
 	if [ -f ${DESTDIR}${ETC_DIR}/colordiffrc ]; then \
 	  mv -f ${DESTDIR}${ETC_DIR}/colordiffrc \
 	    ${DESTDIR}${ETC_DIR}/colordiffrc.old; \
 	else \
 	  install -d ${DESTDIR}${ETC_DIR}; \
 	fi
-	cp colordiffrc ${DESTDIR}${ETC_DIR}/colordiffrc
-	-chown root.root ${DESTDIR}${ETC_DIR}/colordiffrc
-	chmod 644 ${DESTDIR}${ETC_DIR}/colordiffrc
+	install -m 644 colordiffrc ${DESTDIR}${ETC_DIR}/colordiffrc
 
 uninstall:
 	rm -f ${DESTDIR}${INSTALL_DIR}/colordiff
