include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/UnixFormula.mk

Title=		FIGlet
Name=		figlet
Version=	2.2.4
Revision=	0
URL=		ftp://ftp.figlet.org/pub/figlet/program/unix/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE
