include ../../Library/Unix.mk

Title=		FIGlet
Name=		figlet
Version=	2.2.5
Revision=	1
Site=		http://www.figlet.org/
Source=		ftp://ftp.figlet.org/pub/figlet/program/unix//$(Name)-$(Version).tar.gz
License=	The Academic Free License

LicenseFile=	$(SourceDir)/LICENSE

define test_inner_hook
endef
