BuildRequires += /usr/local/lib/libjpeg.la
BuildRequires += /usr/local/lib/liblcms.la

include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		Python Imaging Library
Name=		pil
Version=	1.1.7
Revision=	0
URL=		http://effbot.org/media/downloads/
Source=		Imaging-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	LICENSE

UncompressedName=Imaging-$(Version)