BuildRequires += $(LibDir)/libjpeg.la
BuildRequires += $(LibDir)/liblcms.la

include ../../Library/Python.mk

Title=		Python Imaging Library
Name=		pil
Version=	1.1.7
Revision=	1
URL=		http://effbot.org/media/downloads/
Source=		Imaging-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	LICENSE

UncompressedName = Imaging-$(Version)
