include ../../Library/GNU.mk

Title=		LZO
Name=		lzo
Version=	2.08
Site=		http://www.oberhumer.com/opensource/lzo/
Source=		http://www.oberhumer.com/opensource/lzo/download//$(Name)-$(Version).tar.gz
License=	GPL
