include ../../Library/Config.mk
RUDIX_UNIVERSAL=no
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		LZO
Name=		lzo
Version=	2.06
Revision=	0
URL=		http://www.oberhumer.com/opensource/lzo/download/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING

GnuConfigureExtra += --enable-shared
