include ../../Library/GNU.mk

Title=		SDL2
Name=		sdl2
Version=	2.0.9
Site=		https://www.libsdl.org
Source=		https://libsdl.org/release/SDL2-$(Version).tar.gz
License=        GPL

LicenseFile=	$(BuildDir)/README-SDL.txt
ReadMeFile=	$(BuildDir)/README.txt
