include ../../Library/GNU.mk

BuildRequires += $(LibDir)/libintl.la # gettext

Title=		Fontconfig
Name=		fontconfig
Version=	2.13.0
Site=		https://www.freedesktop.org/wiki/Software/fontconfig/
Source=		https://www.freedesktop.org/software/fontconfig/release/$(Name)-$(Version).tar.bz2
License=	GPL

GnuConfigureExtra +=--disable-docs
