include ../../Library/GNU.mk

Title=		GNU dbm
Name=		gdbm
Version=	1.10
Revision=	0
Site=		http://www.gnu.org.ua/software/gdbm/
URL=		ftp://ftp.gnu.org/gnu/gdbm
Source=		$(Name)-$(Version).tar.gz
License=	GPL

define test_inner_hook
$(BinDir)/testgdbm --version
endef
