include ../../Library/GNU.mk

Title=		Vstr
Name=		vstr
Version=	1.0.15
Revision=	0
Site=		http://www.and.org/vstr/
URL=		http://www.and.org/vstr/latest
Source=		$(Name)-$(Version).tar.bz2
License=	LGPL
