include ../../Library/CMake.mk

Title=		JsonCpp
Name=		jsoncpp
Version=	1.9.4
Site=		https://github.com/open-source-parsers/jsoncpp
Source=		https://github.com/open-source-parsers/jsoncpp/archive/$(Version).tar.gz
License=	Public Domain or MIT
LicenseFile=	$(SourceDir)/LICENSE
ReadMeFile=	$(SourceDir)/README.md
