include ../../Library/GNU.mk

Title=		Quilt: a patch manager
Name=		quilt
Version=	0.65
Site=		http://example.org/
Source=		http://git.savannah.nongnu.org/cgit/quilt.git/snapshot/quilt-$(Version).tar.gz
License=        GPL2

GnuConfigureExtra += --without-getopt
MakeInstallFlags = BUILD_ROOT=$(DestDir)
ReadMeFile=	${BuildDir}/doc/README
