# Config.mk - Global configuration
RUDIX=rudix-snowleopard
RUDIX_UNIVERSAL=yes
RUDIX_DISABLE_DEPENDENCY_TRACKING=yes
RUDIX_SAVE_CONFIGURE_CACHE=yes
RUDIX_STRIP_PACKAGE=yes
RUDIX_ENABLE_NLS=yes
RUDIX_BUILD_WITH_STATIC_LIBS=yes
RUDIX_BUILD_STATIC_LIBS=no
RUDIX_PARALLEL_EXECUTION=yes
RUDIX_LABELS=Rudix-2013,OSX-SnowLeopard,XCode-4.0
RUDIX_PACKAGEMAKER=/Developer/usr/bin/packagemaker
