include ../../Library/GNU.mk

Title=		My Package
Name=		package
Version=	1.2.3
Revision=	0
URL=		http://my.package.com/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE
