include ../../Library/GNU.mk

Title=		TITLE
Name=		NAME
Version=	1.2.3
Revision=	0
URL=		http://path/to/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE
