--- Makefile.orig	2009-08-04 16:49:48.000000000 -0300
+++ Makefile	2009-08-04 16:49:52.000000000 -0300
@@ -112,8 +112,8 @@
 release:  astyle
 astyle:  $(OBJ)
 	@ mkdir -p $(bindir)
-	$(CXX) -o $(bindir)/$@ $^
-	strip $(bindir)/$@
+	$(CXX) $(LDFLAGS) -o $(bindir)/$@ $^
+	#strip $(bindir)/$@
 	@ echo
 
 debug:  astyled
