include ../../Library/GNU.mk

Title=		LibJpeg
Name=		compat-libjpeg
Version=	8d
Revision=	0
URL=		http://www.ijg.org/files/
Source=		jpegsrc.v$(Version).tar.gz

ReadMeFile=	$(SourceDir)/usage.txt
LicenseFile=	$(SourceDir)/README

UncompressedName=jpeg-$(Version)
