include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		SCons
Name=		scons
Version=	2.1.0
Revision=	0
URL=		http://downloads.sourceforge.net/scons
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README.txt
LicenseFile=	$(SourceDir)/LICENSE.txt
