include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		pkg-config
Name=		pkg-config
AltName=	pkg
Version=	0.25
Revision=	4
URL=		http://pkgconfig.freedesktop.org/releases/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
