include ../../Library/CMake.mk

Title=		OpenJPEG
Name=		openjpeg
Version=	2.3.0
Site=		http://www.openjpeg.org
Source=		https://github.com/uclouvain/openjpeg/archive/v2.3.0.tar.gz
License=    GPL
ReadMeFile=	$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/LICENSE

CmakeExtra += -DBUILD_STATIC_LIBS=ON

