include ../../Library/CMake.mk

Title=		Snappy: A fast compressor/decompressor
Name=		snappy
Version=	1.1.7
Site=		http://google.github.io/snappy
Source=		https://github.com/google/snappy/archive/1.1.7.tar.gz
License=        BSD

ReadMeFile = $(SourceDir)/README.md
