include ../../Library/Python.mk

Title=		Pipenv
Name=		python-pipenv
Version=	9.0.3
Site=		https://docs.pipenv.org
Source=		https://github.com/pypa/pipenv/archive/v$(Version).tar.gz
License=	MIT

UncompressedName=pipenv-$(Version)
