BuildRequires += $(BinDir)/erlc # erlang

include ../../Library/Unix.mk

Title=		Elixir
Name=		elixir
Version=	1.0.5
Revision=	0
Site=		http://elixir-lang.org
Source=		https://github.com/elixir-lang/elixir/archive/v$(Version).tar.gz
License=        Apache License

ReadMeFile=	$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/LICENSE
