BuildRequires += $(LibDir)/libogg.la # static-libogg

include ../../Library/GNU.mk

Title=		Libvorbis
Name=		libvorbis
Version=	1.3.3
Site=		http://www.xiph.org/vorbis/
Source=		http://downloads.xiph.org/releases/vorbis//$(Name)-$(Version).tar.gz
License=	BSD
