BuildRequires += $(LibDir)/libogg.la # static-libogg

include ../../Library/GNU.mk

Title=		Libvorbis
Name=		libvorbis
Version=	1.3.3
Revision=	1
URL=		http://downloads.xiph.org/releases/vorbis/
Source=		$(Name)-$(Version).tar.gz
