include ../../Library/GNU.mk

Title=		LibYAML
Name=		libyaml
Version=	0.1.5
Site=		http://pyyaml.org/
Source=		http://pyyaml.org/download/libyaml/yaml-$(Version).tar.gz
License=	MIT
LicenseFile=	$(SourceDir)/LICENSE

UncompressedName=yaml-$(Version)
