include ../../Library/GNU.mk

Title=		LibYAML
Name=		libyaml
Version=	0.1.5
Revision=	0
Site=		http://pyyaml.org/
URL=		http://pyyaml.org/download/libyaml
Source=		yaml-$(Version).tar.gz
License=	MIT
LicenseFile=	$(SourceDir)/LICENSE

UncompressedName=yaml-$(Version)
