BuildRequires += $(LibDir)/libgmp.la # static-gmp
BuildRequires += $(LibDir)/liboop.la # static-liboop
BuildRequires += $(LibDir)/libnettle.a # static-libnettle

include ../../Library/GNU.mk

Title=		LSH (Secure Shell)
Name=		lsh
Version=	2.1
Revision=	0
Site=		http://www.lysator.liu.se/~nisse/lsh/
URL=		http://www.lysator.liu.se/~nisse/archive/
Source=		$(Name)-$(Version).tar.gz
License=	GPL
