BuildRequires += $(LibDir)/libgmp.la # gmp
BuildRequires += $(LibDir)/liboop.la # liboop
BuildRequires += $(LibDir)/libnettle.a # libnettle

include ../../Library/GNU.mk

Title=		LSH (Secure Shell)
Name=		lsh
Version=	2.1
Site=		http://www.lysator.liu.se/~nisse/lsh/
Source=		http://www.lysator.liu.se/~nisse/archive//$(Name)-$(Version).tar.gz
License=	GPL
