BuildRequires += $(BinDir)/pkg-config # pkgconfig

include ../../Library/GNU.mk

Title=		Liboop
Name=		liboop
Version=	1.0
Revision=	0
Site=		http://www.lysator.liu.se/liboop/
Source=		http://download.ofb.net/liboop/${Name}.tar.gz
License=	LGPL

ReadMeFile=	README
