BuildRequires += $(BinDir)/pkg-config # pkgconfig

include ../../Library/GNU.mk

Title=		Liboop (low-level event loop)
Name=		liboop
Version=	1.0
Revision=	0
URL=		http://download.ofb.net/liboop
Source=		${Name}.tar.gz

ReadMeFile=	README
