include ../../Library/GNU.mk

Title=		CTemplate
Name=		ctemplate
Version=	2.2
Site=		https://github.com/olafvdspek/ctemplate
Source=		http://ctemplate.googlecode.com/files//$(Name)-$(Version).tar.gz
License=	BSD
