include ../../Library/GNU.mk

Title=		CTemplate
Name=		ctemplate
Version=	2.2
Site=		http://code.google.com/p/google-ctemplate/
Source=		http://ctemplate.googlecode.com/files//$(Name)-$(Version).tar.gz
License=	BSD
