include ../../Library/GNU.mk

Title=		Integer Set Library
Name=		isl
Version=	0.14
Revision=	0
Site=		http://isl.gforge.inria.fr/user.html
Source=		ftp://gcc.gnu.org/pub/gcc/infrastructure/$(Name)-$(Version).tar.bz2
License=        MIT
LicenseFile=	$(SourceDir)/LICENSE

define test_inner_hook
test -f $(LibDir)/libisl.la
endef
