BuildRequires += $(BinDir)/pcre-config

include ../../Library/GNU.mk

Title=		Apache HTTPd
Name=		httpd
Version=	2.4.1
Revision=	0
URL=		http://ftp.unicamp.br/pub/apache//httpd/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE

#GnuConfigureExtra += --enable-layout=GNU
