include ../../Library/GNU.mk

Title=		NSPR
Name=		nspr
Version=	4.9.4
Revision=	0
URL=		http://ftp.mozilla.org/pub/mozilla.org/nspr/releases/v$(Version)/src
Source=		$(Name)-$(Version).tar.gz

BuildDir=$(SourceDir)/mozilla/nsprpub
ReadMeFile=README
LicenseFile=$(BuildDir)/LICENSE

