--- Makefile.orig	2009-03-24 23:26:53.000000000 -0300
+++ Makefile	2009-03-24 23:27:06.000000000 -0300
@@ -3,7 +3,7 @@
 MANDIR=		$(PREFIX)/share/man
 
 CFLAGS=		-Wall -ansi -pedantic
-CFLAGS+=	-O2
+CFLAGS+=	-O2 $(CFLAGS_EXTRA)
 #CFLAGS+=	-ggdb
 
 # Modern Unixes should run OK on this. On Linux use /dev/urandom (won't block)
