#!/bin/bash

#
# This comes from Homebrew, but is heavily adapted
#

# echo "HOME is $HOME" > /tmp/ntfs3g.install-log
# echo "SUDO_USER = \"$SUDO_USER\"" >> /tmp/ntfs3g.install-log

if [ -z "$SUDO_USER" ]; then
	THISUID=$(id -u $(basename $HOME))
	THISGID=$(id -g $(basename $HOME))
else
	THISUID=$(id -u $SUDO_USER)
	THISGID=$(id -g $SUDO_USER)
fi

# echo "UID is $THISUID" >> /tmp/ntfs3g.install-log
# echo "GID is $THISGID" >> /tmp/ntfs3g.install-log

echo | sed "s/@THISUID@/$THISUID/g
s/@THISGID@/$THISGID/g" > $3/usr/local/sbin/mount_ntfs << EOHERE
#!/bin/bash

VOLUME_NAME="\${@:$#}"
VOLUME_NAME=\${VOLUME_NAME#/Volumes/}
USER_ID=@THISUID@
GROUP_ID=@THISGID@

if [ \`/usr/bin/stat -f %u /dev/console\` -ne 0 ]; then
  USER_ID=\`/usr/bin/stat -f %u /dev/console\`
  GROUP_ID=\`/usr/bin/stat -f %g /dev/console\`
fi

/usr/local/bin/ntfs-3g \\
  -o volname="\${VOLUME_NAME}" \\
  -o local \\
  -o negative_vncache \\
  -o auto_xattr \\
  -o auto_cache \\
  -o noatime \\
  -o windows_names \\
  -o user_xattr \\
  -o inherit \\
  -o uid=\$USER_ID \\
  -o gid=\$GROUP_ID \\
  -o allow_other \\
  "\$@" >> /var/log/mount-ntfs-3g.log 2>&1

exit \$?;
EOHERE
chmod 0755 $3/usr/local/sbin/mount_ntfs
exit 0
