# Requires xz to uncompress the source

include ../../Library/GNU.mk

BuildRequires += $(LibDir)/libglib-2.0.la # glib

Title=		Pango
Name=		pango
Version=	1.30.1
Site=		http://www.pango.org/
Source=		http://ftp.gnome.org/pub/GNOME/sources/pango/1.30/$(Name)-$(Version).tar.xz
License=	LGPL

