# Requires xz to uncompress the source

include ../../Library/GNU.mk

BuildRequires += $(LibDir)/libglib-2.0.la # static-glib

Title=		Pango
Name=		pango
Version=	1.30.1
Revision=	0
URL=		http://ftp.gnome.org/pub/GNOME/sources/pango/1.30
Source=		$(Name)-$(Version).tar.xz

