BuildRequires += $(LibDir)/libjpeg.la # static-libjpeg
BuildRequires += $(LibDir)/libtiff.la # static-libtiff

include ../../Library/GNU.mk

Title=		Little CMS
Name=		compat-lcms
Version=	1.19
Revision=	1
URL=		http://downloads.sourceforge.net/lcms
Source=		lcms-$(Version).tar.gz

UncompressedName=lcms-$(Version)

ReadMeFile=	$(SourceDir)/README.1ST
