# Python Game Development
# http://www.pygame.org/
# LGPL

include ../../Library/Rules.mk
include ../../Library/Python.mk

NAME=		pygame
VERSION=	1.9.1
REVISION=	0
URL=		http://www.pygame.org/ftp/
SOURCE=		$(NAME)-$(VERSION)release.tar.gz
UNCOMPRESSEDDIR= $(NAME)-$(VERSION)release
