include ../../Library/GNU.mk

Title=		LibFFI
Name=		libffi
Version=	3.4.2
Site=		https://sourceware.org/libffi/
Source=		https://github.com/libffi/libffi/releases/download/v$(Version)/libffi-$(Version).tar.gz
License=	MIT

ReadMeFile=	$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/LICENSE
