include ../../Library/GNU.mk

Title=		LibFFI
Name=		libffi
Version=	3.2.1
Site=		https://sourceware.org/libffi/
Source=		ftp://sourceware.org/pub/libffi/libffi-$(Version).tar.gz
License=	MIT

LicenseFile=	$(SourceDir)/LICENSE
