BuildRequires += $(LibDir)/libjpeg.la
BuildRequires += $(LibDir)/liblcms.la

include ../../Library/Python.mk

Title=		Python Imaging Library (fork)
Name=		pillow
Version=	1.7.7
Revision=	0
URL=		http://pypi.python.org/packages/source/P/Pillow/
Source=		Pillow-$(Version).zip

ReadMeFile=	$(SourceDir)/README.rst
LicenseFile=	$(SourceDir)/PKG-INFO

UncompressedName = Pillow-$(Version)
