BuildRequires += /usr/local/lib/libjpeg.la
BuildRequires += /usr/local/lib/liblcms.la

include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		Python Imaging Library (fork)
Name=		pillow
Version=	1.7.6
Revision=	0
URL=		http://pypi.python.org/packages/source/P/Pillow/
Source=		Pillow-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README.rst
LicenseFile=	$(SourceDir)/PKG-INFO

UncompressedName=Pillow-$(Version)