include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Site=		http://zsync.moria.org.uk/
License=	Artistic License
Description=	Client-side implementation of the rsync algorithm
Title=		zsync $(Version)
Name=		zsync
Version=	0.6.2
Revision=	2
URL=		http://zsync.moria.org.uk/download/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(BuildDir)/README
LicenseFile=	$(BuildDir)/COPYING
