include ../../Library/GNU.mk

Title=		Zsync
Name=		zsync
Version=	0.6.2
Revision=	5
URL=		http://zsync.moria.org.uk/download/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
