include ../../Library/GNU.mk

Title=		EPIC5
Name=		epic5
Version=	1.1.6
Revision=	0
URL=		http://ftp.epicsol.org/pub/epic/EPIC5-PRODUCTION/
Source=		$(Name)-$(Version).tar.bz2

LicenseFile=	$(SourceDir)/COPYRIGHT

define test_inner_hook
$(BinDir)/epic5 -v
endef
