include ../../Library/GNU.mk

Title=		Hexedit
Name=		hexedit
Version=	1.2.12
Revision=	7
Site=		http://www.chez.com/prigaux/hexedit.html
Source=		http://www.chez.com/prigaux//$(Name)-$(Version).src.tgz
License=	GPL

ReadMeFile=	README
UncompressedName = hexedit
