include ../../Library/GNU.mk

Title=		hexedit
Name=		hexedit
Version=	1.2.12
Revision=	6
URL=		http://www.chez.com/prigaux/
Source=		$(Name)-$(Version).src.tgz

ReadMeFile=	$(PortDir)/ReadMe.txt
LicenseFile=	$(SourceDir)/COPYING

UncompressedName = hexedit
