include ../../Library/Python.mk

Title=		Html2text
Name=		html2text
Version=	3.200.3
Revision=	1
Site=		https://github.com/aaronsw/html2text
Source=		https://github.com/aaronsw/html2text/tarball/master
License=	GPL
UncompressedName=aaronsw-html2text-8ddc844

ReadMeFile=	$(SourceDir)/README.md

define test_inner_hook
$(BinDir)/html2text --version
endef
