include ../../Library/GNU.mk

Title=		LAME
Name=		lame
Version=	3.99.5
Revision=	0
URL=		http://sourceforge.net/projects/lame/files/lame/3.99/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
