BuildRequires += $(LibDir)/libintl.la
BuildRequires += $(LibDir)/libntlm.la
BuildRequires += $(LibDir)/libidn.la

include ../../Library/GNU.mk

Title=		GNU SASL Library
Name=		libgsasl
Version=	1.8.0
Site=		$(GnuHome)/$(Name)
Source=		$(GnuMirror)/gsasl//$(Name)-$(Version).tar.gz
License=	GPL
