BuildRequires += $(LibDir)/libintl.la
BuildRequires += $(LibDir)/libntlm.la
BuildRequires += $(LibDir)/libidn.la

include ../../Library/GNU.mk

Title=		GNU SASL Library
Name=		libgsasl
Version=	1.8.0
Revision=	0
Site=		http://www.gnu.org/software/gsasl/
Source=		http://ftp.gnu.org/gnu/gsasl//$(Name)-$(Version).tar.gz
License=	GPL
