BuildRequires += $(LibDir)/libintl.la
BuildRequires += $(LibDir)/libntlm.la
BuildRequires += $(LibDir)/libidn.la

include ../../Library/GNU.mk

Title=		GNU SASL Library
Name=		libgsasl
Version=	1.8.0
Revision=	0
URL=		http://ftp.gnu.org/gnu/gsasl/
Source=		$(Name)-$(Version).tar.gz
