--- makefile.orig	2014-03-01 13:51:20.000000000 -0300
+++ makefile	2014-03-01 13:52:09.000000000 -0300
@@ -1,14 +1,13 @@
 #
 # Makefile for UNIX - unrar
 
-# Linux using GCC
+# OSX using clang
 CXX=g++
-CXXFLAGS=-O2
-LIBFLAGS=-fPIC
+CXXFLAGS=-Os
 DEFINES=-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DRAR_SMP
 STRIP=strip
 LDFLAGS=-pthread
-DESTDIR=/usr
+DESTDIR=/usr/local
 
 # Linux using LCC
 #CXX=lcc
@@ -136,7 +135,8 @@
 	$(LINK) -shared -o libunrar.so $(LDFLAGS) $(OBJECTS) $(LIB_OBJ)
 
 install-unrar:
-			install -D unrar $(DESTDIR)/bin/unrar
+			install -d $(DESTDIR)/bin
+			install -m 755 unrar $(DESTDIR)/bin/unrar
 
 uninstall-unrar:
 			rm -f $(DESTDIR)/bin/unrar
