include ../../Library/GNU.mk

Title=		GC
Name=		gc
Version=	7.2
Revision=	0
URL=		http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/doc/README
LicenseFile=	$(SourceDir)/include/gc.h

GnuConfigureExtra += --enable-cplusplu
