include ../../Library/GNU.mk

Title=		Boehm-Demers-Weiser GC
Name=		gc
Version=	7.2f
Revision=	0
Site=		http://hboehm.info/gc/
Source=		http://hboehm.info/gc/gc_source//$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/doc/README
LicenseFile=	$(SourceDir)/include/gc.h

UncompressedName=gc-7.2

GnuConfigureExtra += --enable-cplusplu
