include ../../Library/Configure.mk

Title=		Talloc
Name=		talloc
Version=	2.0.8
Revision=	0
URL=		http://samba.org/ftp/talloc
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	README
LicenseFile=	LICENSE
