include ../../Library/GNU.mk

Title=		LibJPEG
Name=		libjpeg
Version=	9a
Revision=	0
URL=		http://www.ijg.org/files/
Source=		jpegsrc.v$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	LICENSE

UncompressedName=jpeg-$(Version)
