include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		LibJpeg
Name=		libjpeg
Version=	8c
Revision=	1
URL=		http://www.ijg.org/files/
Source=		jpegsrc.v$(Version).tar.gz

ReadMeFile=	$(BuildDir)/README
LicenseFile=	$(BuildDir)/README

UncompressedName= jpeg-$(Version)
