include ../../Library/GNU.mk

Title=		LibJPEG
Name=		libjpeg
Version=	9a
Site=		http://www.ijg.org/
Source=		http://www.ijg.org/files/jpegsrc.v$(Version).tar.gz
License=	BSD-like

ReadMeFile=	$(SourceDir)/README
LicenseFile=	LICENSE

UncompressedName=jpeg-$(Version)
