include ../../Library/GNU.mk

Title=		kconfig frontends
Name=		kconfig-frontends
Version=	4.11.0.1
Site=		http://ymorin.is-a-geek.org/projects/kconfig-frontends
Source=		http://ymorin.is-a-geek.org/download/$(Name)/$(Name)-$(Version).tar.bz2
License=	GPL
Description=	Linux kernel configuration (aka kconfig) parser and frontends

ReadMeFile=     $(SourceDir)/README
LicenseFile=    $(SourceDir)/COPYING
