include ../../Library/GNU.mk

Title=		Jemalloc
Name=		jemalloc
Version=	4.4.0
Site=		http://www.canonware.com/jemalloc/
Source=		https://github.com/jemalloc/jemalloc/releases/download/$(Version)/jemalloc-$(Version).tar.bz2
License=        BSD-derived
