include ../../Library/GNU.mk

Title=		Links
Name=		links
Version=	2.7
Revision=	0
URL=		http://links.twibright.com/download
Source=		$(Name)-$(Version).tar.bz2

define test_inner_hook
$(BinDir)/links -version
endef
