include ../../Library/CMake.mk

Title=		STLink
Name=		stlink
Version=	1.6.0
Site=		http://example.org/
Source=		https://github.com/texane/stlink/archive/v$(Version).tar.gz
License=        BSD
ReadMeFile=	${SourceDir}/README.md
LicenseFile=	${SourceDir}/LICENSE.md

BuildRequires += $(BinDir)/pkg-config	# pkgconfig
BuildRequires += $(LibDir)/libusb-*.la	# libusb | libusb
