include ../../Library/CMake.mk

Title=		STLink
Name=		stlink
Version=	1.5.1
Site=		http://example.org/
Source=		https://github.com/texane/stlink/archive/v$(Version).tar.gz
License=        BSD

BuildRequires += $(BinDir)/pkg-config	# pkgconfig
BuildRequires += $(LibDir)/libusb-*.la	# libusb | static-libusb
