include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		virtualenv
Name=		virtualenv
Version=	1.7.1.2
Revision=	0
URL=		http://pypi.python.org/packages/source/v/virtualenv/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/docs/index.txt
LicenseFile=	$(SourceDir)/license.txt
