include ../../Library/GNU.mk

Title=		Libpipeline
Name=		libpipeline
Version=	1.2.2
Revision=	0
Site=		http://www.nongnu.org/libpipeline/
URL=		http://download.savannah.gnu.org/releases/libpipeline
Source=		$(Name)-$(Version).tar.gz
License=	GPL
