include ../../Library/GNU.mk

Title=		Libpipeline
Name=		libpipeline
Version=	1.4.0
Revision=	0
Site=		http://www.nongnu.org/libpipeline/
Source=		http://download.savannah.gnu.org/releases/libpipeline/$(Name)-$(Version).tar.gz
License=	GPL
