include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		Fabric
Name=		fabric
Version=	1.4.0
Revision=	0
URL=		http://pypi.python.org/packages/source/F/Fabric/
Source=		Fabric-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/LICENSE

