include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	Code browsing program
Site=		http://cscope.sourceforge.net/
License=	BSD
Title=		Cscope $(Version)
Name=		cscope
Version=	15.7a
Revision=	1
URL=		http://downloads.sourceforge.net/$(Name)
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING

