include ../../Library/GNU.mk

Title=		WebP
Name=		libwebp
Version=	1.0.0
Site=		https://developers.google.com/speed/webp
Source=		https://storage.googleapis.com/downloads.webmproject.org/releases/webp/${Name}-${Version}.tar.gz
License=    GPL
