include ../../Library/CMake.mk

Title=		Libproxy
Name=		libproxy
Version=	0.4.15
Sirce=		https://libproxy.github.io/libproxy/
Source=		https://github.com/libproxy/libproxy/releases/download/$(Version)/libproxy-$(Version).tar.xz
License=	LGPLv2+
