# Requires MySQL Community Server installed to compile.
# Download it from here: http://dev.mysql.com/downloads/mysql/

include ../../Library/Python.mk

Title=		MySQLdb (Python Module)
Name=		mysqldb
Version=	1.2.3
Revision=	0
Site=		http://sourceforge.net/projects/mysql-python/
URL=		http://download.sourceforge.net/sourceforge/mysql-python/
Site=		http://sourceforge.net/projects/mysql-python/
URL=		http://sourceforge.net/projects/mysql-python/files/mysql-python/$(Version)/
Source=		MySQL-python-$(Version).tar.gz
License=	GPL

LicenseFile=	$(SourceDir)/PKG-INFO

UncompressedName = MySQL-python-$(Version)
