# Requires MySQL Community Server installed to compile.
# Download it from here: http://dev.mysql.com/downloads/mysql/

include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		MySQLdb (Python Module)
Name=		mysqldb
Version=	1.2.3
Revision=	0
URL=		http://download.sourceforge.net/sourceforge/mysql-python/
URL=		http://sourceforge.net/projects/mysql-python/files/mysql-python/$(Version)/
Source=		MySQL-python-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/PKG-INFO

UncompressedName = MySQL-python-$(Version)
