include ../../Library/GNU.mk

Title=		Librsync
Name=		librsync
Version=	0.9.7
Site=		http://librsync.sourceforge.net/
Source=		http://downloads.sourceforge.net/$(Name)/$(Name)-$(Version).tar.gz
License=	LGPL

MakeExtra += LDFLAGS="$(LdFlags)"
