include ../../Library/GNU.mk

Title=		JSON-C
Name=		json-c
Version=	0.9
Revision=	3
Site=		http://oss.metaparadigm.com/json-c/
URL=		http://oss.metaparadigm.com/json-c/
Source=		$(Name)-$(Version).tar.gz
License=	BSD
