include ../../Library/CMake.mk

Title=		JSON-C
Name=		json-c
Version=	0.15
Site=		https://github.com/json-c/json-c
Source=		https://github.com/json-c/json-c/archive/json-c-$(Version)-20200726.tar.gz
License=	MIT

UncompressedName=json-c-json-c-$(Version)-20200726
