BuildRequires += $(LibDir)/libjpeg.la # static-libjpeg
BuildRequires += $(LibDir)/libtiff.la # static-libtiff

include ../../Library/GNU.mk

Title=		Little CMS
Name=		lcms
Version=	2.5
Revision=	0
Site=		http://www.littlecms.com/
URL=		http://downloads.sourceforge.net/lcms
Source=		$(Name)2-$(Version).tar.gz
License=	MIT

UncompressedName = lcms2-$(Version)

ReadMeFile=	$(SourceDir)/README.1ST
