BuildRequires += $(LibDir)/libjpeg.la

include ../../Library/GNU.mk

Title=		Little CMS
Name=		lcms2
Version=	2.3
Revision=	0
URL=		http://sourceforge.net/projects/lcms/files/lcms/$(Version)/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	README
LicenseFile=	$(SourceDir)/COPYING
