include ../../Library/GNU.mk

Title=		Argtable
Name=		argtable
Version=	2.13
Revision=	1
URL=		http://sourceforge.net/projects/argtable/files/argtable/argtable-$(Version)/
Source=		$(Name)2-13.tar.gz


UncompressedName = $(Name)2-13
