include ../../Library/GNU.mk

Title=		Argtable
Name=		argtable
Version=	2.13
Revision=	1
URL=		http://sourceforge.net/projects/argtable/files/argtable/argtable-$(Version)/
Source=		$(Name)2-13.tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING

UncompressedName = $(Name)2-13
