include ../../Library/GNU.mk

Title=		Pipe Viewer
Name=		pv
Version=	1.4.4
Revision=	0
URL=		http://www.ivarch.com/programs/sources/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/doc/COPYING
