include ../../Library/GNU.mk

Title=		tshark
Name=		tshark
Version=	2.6.10
Site=		https://www.wireshark.org/
Source=		https://www.wireshark.org/download/src/all-versions/wireshark-$(Version).tar.xz
License=	GPLv3

GnuConfigureExtra += --disable-guides --disable-wireshark

UncompressedName= wireshark-$(Version)

ReadMeFile=	$(BuildDir)/README.md
