include ../../Library/GNU.mk

Title=		tshark
Name=		tshark
Version=	2.6.5
Site=		https://www.wireshark.org/
Source=		https://1.eu.dl.wireshark.org/src/wireshark-$(Version).tar.xz
License=	GPLv3

GnuConfigureExtra += --disable-guides --disable-wireshark

UncompressedName= wireshark-$(Version)

ReadMeFile=	$(BuildDir)/README.md
