include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		httplib2 (Python Module)
Name=		httplib2
Version=	0.7.4
Revision=	0
URL=		http://pypi.python.org/packages/source/h/httplib2/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/PKG-INFO

