include ../../Library/GNU.mk

Title=		Freetype
Name=		freetype
Version=	2.5.2
Revision=	0
URL=		http://download.savannah.gnu.org/releases/freetype/
Source=		$(Name)-$(Version).tar.gz
LicenseFile=	$(SourceDir)/docs/LICENSE.txt
