include ../../Library/GNU.mk

Title=		Freetype
Name=		freetype
Version=	2.5.2
Site=		http://www.freetype.org/
Source=		http://download.savannah.gnu.org/releases/freetype//$(Name)-$(Version).tar.gz
License=	FTP/GPL Version 2
LicenseFile=	$(SourceDir)/docs/LICENSE.txt
