include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		ntop
Name=		ntop
Version=	4.1.0
Revision=	0
URL=		http://sourceforge.net/projects/ntop/files/ntop/Stable/
Source=		$(Name)-$(Version).tar.gz
