include ../../Library/Unix.mk

Title=		WBox
Name=		wbox
Version=	5
Revision=	0
URL=		http://hping.org/wbox/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
