include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	Compression program, similar in functionality to gzip or bzip2, but able to take advantage long distance redundencies in file
Site=		http://rzip.samba.org/
License=	GPL
Title=		rzip
Name=		rzip
Version=	2.1
Revision=	14
URL=		http://rzip.samba.org/ftp/rzip/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(PortDir)/README.txt
LicenseFile=	$(SourceDir)/COPYING
