include ../../Library/GNU.mk

Title=		Libxmp
Name=		libxmp
Version=	4.0.2
Revision=	0
URL=		http://sourceforge.net/projects/xmp/files/libxmp/$(Version)
Source=		$(Name)-$(Version).tar.gz

LicenseFile=	$(SourceDir)/docs/COPYING.LIB
