include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		GNU cflow
Name=		cflow
Version=	1.4
Revision=	0
URL=		http://ftp.gnu.org/gnu/cflow/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
