include ../../Library/GNU.mk

Title=		PortAudio
Name=		portaudio
Version=	v19
DateVersion=	20140130
Revision=	0
Site=		http://www.portaudio.com
URL=		http://www.portaudio.com/archives
Source=		pa_stable_$(Version)_$(DateVersion).tgz
License=	MIT

ReadMeFile=$(SourceDir)/README.txt
LicenseFile=$(SourceDir)/LICENSE.txt

UncompressedName=portaudio
