include ../../Library/GNU.mk

Title=		MLZ-libcerf
Name=		libcerf
Version=	1.10
Site=		http://apps.jcns.fz-juelich.de/doku/sc/libcerf
Source=		http://apps.jcns.fz-juelich.de/src/$(Name)/$(Name)-$(Version).tgz
License=        GPL
