include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		aria2
Name=		aria2
Version=	1.12.1
Revision=	0
URL=		http://downloads.sourceforge.net/aria2
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(BuildDir)/README.asciidoc
LicenseFile=	$(BuildDir)/COPYING

GnuConfigureExtra += --with-included-gettext
