include ../../Library/GNU.mk

Title=		aria2
Name=		aria2
Version=	1.14.1
Revision=	0
URL=		http://downloads.sourceforge.net/aria2
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README.asciidoc
LicenseFile=	$(SourceDir)/COPYING

GnuConfigureExtra += --with-included-gettext
