include ../../Library/GNU.mk

Title=		GNU libunistring
Name=		libunistring
Version=	0.9.3
Revision=	3
Site=		http://www.gnu.org/s/libunistring/
URL=		http://ftp.gnu.org/gnu/libunistring/
Source=		$(Name)-$(Version).tar.gz
License=	GPL
