include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	Provides functions for manipulating Unicode strings
Site=		http://www.gnu.org/s/libunistring/
License=	GPL
Title=		libunistring
Name=		libunistring
Version=	0.9.3
Revision=	0
URL=		http://ftp.gnu.org/gnu/libunistring/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
