include ../../Library/GNU.mk

Title=		GNU libunistring
Name=		libunistring
Version=	0.9.3
Revision=	2
URL=		http://ftp.gnu.org/gnu/libunistring/
Source=		$(Name)-$(Version).tar.gz


ifdef ONLY_STATIC_LIBS
GnuConfigureExtra += --enable-static --disable-shared
endif
