#!/bin/sh
[ ! -f $3/usr/local/share/nginx/html/index.html ] && \
    install -m 644 $3/usr/local/share/nginx/html/index.html.default $3/usr/local/share/nginx/html/index.html
[ ! -f $3/usr/local/share/nginx/html/50x.html ] && \
  install -m 644 $3/usr/local/share/nginx/html/50x.html.default $3/usr/local/share/nginx/html/50x.html
for x in fastcgi.conf fastcgi_params mime.types nginx.conf scgi_params uwsgi_params ; do \
    [ ! -f $3/usr/local/etc/nginx/$x ] && \
    install -m 644 $3/usr/local/etc/nginx/$x.default $3/usr/local/etc/nginx/$x
done
exit 0
