# $Id: Makefile,v 1.1.1.1 2009/03/01 15:03:53 ruda Exp $
#
# Copyright (c) 2007-2008 Ruda Moura <ruda@rudix.org>
#

Rules = retrieve prep build install html download
Rules += installpkg pkg dmg
Rules += installclean clean distclean realdistclean pkgclean dmgclean

Ports := $(wildcard [a-z]*)

$(Rules):
	@for port in $(Ports) ; do \
		( cd $$port ; $(MAKE) $@ ) ; \
	done

world: about
