include ../../Library/GNU.mk

Title=		Gloox
Name=		gloox
Version=	1.0.3
Revision=	0
Site=		http://camaya.net/gloox
Source=		http://camaya.net/download//$(Name)-$(Version).tar.bz2
License=	GPL

CFlags += -Wno-long-long
