include ../../Library/GNU.mk

Title=		Bvi
Name=		bvi
Version=	1.3.2
Revision=	10
URL=		http://downloads.sourceforge.net/$(Name)
Source=		$(Name)-$(Version).src.tar.gz

define test_inner_hook
$(BinDir)/bvi -c q
endef
