include ../../Library/GNU.mk

Title=		Bvi
Name=		bvi
Version=	1.3.2
Site=		http://bvi.sourceforge.net/
Source=		http://downloads.sourceforge.net/$(Name)/$(Name)-$(Version).src.tar.gz
License=	GPL

define test_hook
$(BinDir)/bvi -c q
endef
