include ../../Library/GNU.mk

Title=		GNU libsigsegv
Name=		libsigsegv
Version=	2.10
Revision=	0
Site=		http://libsigsegv.sourceforge.net/
Source=		http://ftp.gnu.org/gnu/libsigsegv//$(Name)-$(Version).tar.gz
License=	GPL
