# FIXME: build with libintl

include ../../Library/GNU.mk

Title=		Popt
Name=		popt
Version=	1.16
Revision=	0
URL=		http://rpm5.org/files/popt/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING

# ifdef WITHOUT_NLS
# NLS=		--disable-nls
# else
# NLS=		--enable-nls
# DEPENDS=	$(LibDir)/libintl.la
# endif

# ifdef WITH_STATIC_NLS
# LDFLAGS+=	-framework CoreFoundation -liconv
# endif

# ifdef STATIC_ONLY
# STATIC=		--enable-static --disable-shared
# endif
