include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	Library for dynamic creation of images
#Site=		http://www.libgd.org/ # is down
Site=		http://www.boutell.com/gd/
License=	
Title=		GD library
Name=		libgd
Version=	2.0.35
Revision=	0
URL=		http://www.libgd.org/releases/
Source=		gd-$(Version).tar.bz2
