include ../../Library/GNU.mk

Title=		LibGD
Name=		libgd
Version=	2.2.5
Site=		https://github.com/libgd
Source=		https://github.com/libgd/libgd/releases/download/gd-${Version}/${Name}-${Version}.tar.xz
License=    Freely distributable
ReadMeFile=	$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/COPYING

ConfigureExtras += --without-xpm
