include ../../Library/GNU.mk

Title=		Iperf
Name=		iperf
Version=	2.0.5
Revision=	2
URL=		http://downloads.sourceforge.net/iperf
Source=		$(Name)-$(Version).tar.gz

define test_inner_hook
$(BinDir)/iperf
endef
