#!/bin/bash

VOLUME_NAME="${@:$#}"
VOLUME_NAME=${VOLUME_NAME#/Volumes/}
USER_ID=502
GROUP_ID=20

if [ `/usr/bin/stat -f %u /dev/console` -ne 0 ]; then
  USER_ID=`/usr/bin/stat -f %u /dev/console`
  GROUP_ID=`/usr/bin/stat -f %g /dev/console`
fi

/usr/local/bin/ntfs-3g \
  -o volname="${VOLUME_NAME}" \
  -o local \
  -o negative_vncache \
  -o auto_xattr \
  -o auto_cache \
  -o noatime \
  -o windows_names \
  -o user_xattr \
  -o inherit \
  -o uid=$USER_ID \
  -o gid=$GROUP_ID \
  -o allow_other \
  "$@" >> /var/log/mount-ntfs-3g.log 2>&1

exit $?;
