.\"
.\" Copyright (c) 2005-2012 Ruda Moura
.\"
.Dd May 13, 2012
.Dt RUDIX 1
.Os
.Sh NAME
.Nm rudix
.Nd Rudix Package Manager
.Sh SYNOPSIS
.Nm
.Op Fl h | v | a | A | l | R | K | u | z
.Op Fl i Ar pkg-path
.Op Fl r Ar package-id
.Op Fl I Ar package-id
.Op Fl L Ar package-id
.Op Fl s Ar package-id
.Op Fl S Ar path
.Op Fl V Ar package-id
.Op Fl f Ar package-id
.Op Fl n Ar package-id
.Sh DESCRIPTION
The
.Nm
utility is the package manager for Rudix therefore you can use it to install, remove, print information about packages and search files under the Rudix domain. It is possible to verify the integrity of installed packages and to fix (repair) packages.
.Pp
Every package has a unique identifier (package-id) and you may refer to Rudix packages by using its full package-id or with its short alias. For example, package Compiler Cache's package-id is org.rudix.pkg.ccache but you can use ccache as an alias.
.Pp
Without any arguments provided,
.Nm
prints a list of packages installed.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl h
Print help on screen and exit.
.It Fl v
Print version and copyright information.
.It Fl a
Print all packages available for installation (name-version-release).
.It Fl A
Print all aliases.
.It Fl l
Print a list of packages with package-id, version and install date.
.It Fl i Ar pkg-path
Install package. If pkg-path is not a file then try to install the package from the Internet. This operation requires root privileges.
.It Fl n Ar package-id
Remote install package. This operation requires root privileges.
.It Fl u
Remote update installed packages. This operation requires root privileges.
.It Fl r Ar package-id
Remove package. This operation requires root privileges.
.It Fl R
Remove all installed packages. This operation requires root privileges.
.It Fl I Ar package-id
Print package-id version and install date.
.It Fl L Ar package-id
List package files.
.It Fl s Ar package-id
List available versions for package-id.
.It Fl S Ar path
Print all packages that contains path.
.It Fl V Ar package-id
Verify package-id.
.It Fl K
Verify all installed packages.
.It Fl f Ar package-id
Fix (repair) package-id. This operation requires root privileges.
.It Fl z
Enter interactive mode (type exit to quit).
.El
.Sh COMMANDS
The
.Nm
utility accepts simple commands which are related to the options seen above.
The list of commands are: help, version, available, aliases, list, remove-all, verify-all, update, interactive, info, files, install, remove, search, owner, verify, fix.
.Sh SEE ALSO
.Xr pkgutil 1 ,
.Xr installer 8 ,
.Xr packagemaker 1
