include ../../Library/GNU.mk

Title=		Wxwidgets
Name=		wxwidgets
Version=	3.0.2
Revision=	0
Site=		https://www.wxwidgets.org/
Source=		https://sourceforge.net/projects/wxwindows/files/$(Version)/wxWidgets-$(Version).tar.bz2
License=	LGPL
ReadMeFile=	$(SourceDir)/docs/readme.txt
LicenseFile=	$(SourceDir)/docs/licence.txt
