include ../../Library/GNU.mk

Title=		GnuTLS
Name=		gnutls
MajorVersion=	3.6
Version=	3.6.5
Site=		http://gnutls.org
Source= 	https://www.gnupg.org/ftp/gcrypt/$(Name)/v$(MajorVersion)/$(Name)-$(Version).tar.xz
License=	LGPLv2.1+

ReadMeFile=	$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/doc/COPYING.LESSER
