include ../../Library/GNU.mk

Title=		GnuTLS
Name=		gnutls
Version=	3.6.9
Site=		https://gnutls.org
Source=		ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/$(Name)-$(Version).tar.xz
License=	LGPLv2.1+

GnuConfigureExtra += --with-included-libtasn1

ReadMeFile=		$(SourceDir)/README.md
LicenseFile=	$(SourceDir)/doc/COPYING.LESSER
