include ../../Library/GNU.mk

Title=		Libusb
Name=		libusb
Version=	1.0.9
Revision=	1
Site=		http://www.libusb.org/
Source=		http://downloads.sourceforge.net/libusb/$(Name)-$(Version).tar.bz2
License=	LGPL
