include ../../Library/GNU.mk

Title=		Libusb
Name=		libusb
Version=	1.0.9
Revision=	0
URL=		http://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-$(Version)/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
