include ../../Library/Python.mk

Title=		meld3
Name=		meld3
Version=	0.6.8
Revision=	0
URL=		http://pypi.python.org/packages/source/m/meld3/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README.txt
LicenseFile=	$(SourceDir)/COPYRIGHT.txt
