include ../../Library/GNU.mk

# 		Collection of over 500 reusable autoconf macros
Title=		Autoconf archive 
Name=		autoconf-archive
Version=	2019.01.06
Site=		$(GnuHome)/$(Name)
Source=		$(GnuMirror)/$(Name)/$(Name)-$(Version).tar.xz
License=        GPL
