include ../../Library/GNU.mk

# 		Collection of over 500 reusable autoconf macros
Title=		Autoconf archive 2018.03.13
Name=		autoconf-archive
Version=	2018.03.13
Site=		https://savannah.gnu.org/projects/autoconf-archive
Source=		https://ftp.gnu.org/gnu/autoconf-archive/autoconf-archive-2018.03.13.tar.xz
License=        GPL
