include ../../Library/GNU.mk

# 		Collection of over 500 reusable autoconf macros
Title=		Autoconf archive 
Name=		autoconf-archive
Version=	2019.01.06
Site=		https://www.gnu.org/software/$(Name)
Source=		http://ftpmirror.gnu.org/$(Name)/$(Name)-$(Version).tar.xz
License=        GPL
