include ../../Library/GNU.mk

Title=		GNU Scientific Library
Name=		gsl
Version=	2.6
Site=		https://www.gnu.org/software/$(Name)
Source=		http://ftpmirror.gnu.org/$(Name)/$(Name)-$(Version).tar.gz
License=        GPL3

# GnuConfigureExtra += --without-gui

# define test_hook
# $(BinDir)/pspp --version | grep $(Version)
# endef
