include ../../Library/GNU.mk

Title=		GNU Scientific Library
Name=		gsl
Version=	2.6
Site=		$(GnuHome)/$(Name)
Source=		$(GnuMirror)/$(Name)/$(Name)-$(Version).tar.gz
License=        GPL3

# GnuConfigureExtra += --without-gui

# define test_hook
# $(BinDir)/pspp --version | grep $(Version)
# endef
