include ../../Library/GNU.mk

Title=		Dumb Networking Library
Name=		libdnet
Version=	1.12
Site=		http://code.google.com/p/libdnet/
Source=		http://libdnet.googlecode.com/files//$(Name)-$(Version).tgz
License=	BSD

LicenseFile=	$(SourceDir)/LICENSE

define test_hook
$(BinDir)/dnet-config --version
endef
