include ../../Library/GNU.mk

Title=		GNU MP
Name=		compat-gmp
Version=	4.3.2
Revision=	4
URL=		http://ftp.gnu.org/gnu/gmp/
Source=		gmp-$(Version).tar.bz2

UncompressedName = gmp-$(Version)

GnuConfigureExtra += --enable-cxx
