include ../../Library/CMake.mk

Title=		MLZ-libcerf
Name=		libcerf
Version=	1.10
Site=		http://apps.jcns.fz-juelich.de/doku/sc/libcerf
Source=		http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.10.tgz
License=    GPL
