include ../../Library/CMake.mk

Title=		libcerf
Name=		libcerf
Version=	1.11
Site=		http://apps.jcns.fz-juelich.de/doku/sc/libcerf
Source=		http://apps.jcns.fz-juelich.de/src/$(Name)/$(Name)-$(Version).tgz
License=	GPLv3
