include ../../Library/GNU.mk

Title=		GNU Aspell EN Dictionary
Name=		aspell6-en
Version=	7.1-0
Site=		ftp://ftp.gnu.org/gnu/aspell/dict/en/
Source=		ftp://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-7.1-0.tar.bz2
License=        GPL
