#!/bin/sh
[ ! -f $3/usr/local/etc/squid.conf ] && \
    install -m 644 $3/usr/local/etc/squid.conf.default $3/usr/local/etc/squid.conf
[ ! -f /usr/local/etc/mime.conf ] && \
    install -m 644 $3/usr/local/etc/mime.conf.default $3/usr/local/etc/mime.conf
[ ! -f /usr/local/etc/cachemgr.conf ] && \
    install -m 644 $3/usr/local/etc/cachemgr.conf.default $3/usr/local/etc/cachemgr.conf
exit 0
