include ../../Library/GNU.mk

Title=		ImageMagick
Name=		imagemagick
Version=	7.0.8-23
Site=		http://www.imagemagick.org
Source=		https://github.com/ImageMagick/ImageMagick/archive/$(Version).tar.gz
License=        GPL

#GnuConfigureExtra=	--without-x
ReadMeFile= 	$(BuildDir)/README.txt
InstallFile=	$(BuildDir)/Install-mac.txt
LicenseFile=	$(BuildDir)/LICENSE
