include ../../Library/Python.mk

Title=		Mocking and Testing Library
Name=		mock
DistName=	python-mock
Version=	1.0.1
Site=           http://www.voidspace.org.uk/python/mock/
Source=		https://pypi.python.org/packages/source/m/mock//$(Name)-$(Version).tar.gz
License=        BSD

ReadMeFile=	$(SourceDir)/README.txt
LicenseFile=	$(SourceDir)/LICENSE.txt
