# Qichang Liang <kcleung@cs.otago.ac.nz>

include ../../Library/GNU.mk

Title=		abnfgen
Name=		abnfgen
Version=	0.16
Revision=	1
Site=		http://www.quut.com/abnfgen/
URL=		http://www.quut.com/abnfgen/
Source=		$(Name)-$(Version).tar.gz
License=	while copyrighted, free for any use
