include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		pylibmc
Name=		pylibmc
Version=	1.2.2
Revision=	1
URL=		http://pypi.python.org/packages/source/p/pylibmc/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README.rst
LicenseFile=	$(SourceDir)/LICENSE
