include ../../Library/GNU.mk

Title=		GNU RCS
Name=		rcs
Version=	5.9.0
Revision=	0
URL=		http://ftp.gnu.org/gnu/rcs/
Source=		$(Name)-$(Version).tar.xz

define test_inner_hook
$(BinDir)/rcs --version
endef
