# Suggested by @brunotikami 

include ../../Library/GNU.mk

Title=		TCP Flow Recorder
Name=		tcpflow
Version=	0.21
Revision=	1
Site=		http://www.circlemud.org/jelson/software/tcpflow/
Source=		http://www.circlemud.org/pub/jelson/tcpflow//$(Name)-$(Version).tar.gz
License=	GPL

LicenseFile=	$(SourceDir)/AUTHORS

GnuConfigureExtra += --host=i386-pc-freebsd
