# Suggested by @brunotikami 

include ../../Library/GNU.mk

Title=		TCP Flow Recorder
Name=		tcpflow
Version=	0.21
Revision=	1
URL=		http://www.circlemud.org/pub/jelson/tcpflow/
Source=		$(Name)-$(Version).tar.gz

LicenseFile=	$(SourceDir)/AUTHORS

GnuConfigureExtra += --host=i386-pc-freebsd
