include ../../Library/GNU.mk

Title=		Libntlm
Name=		libntlm
Version=	1.4
Revision=	1
Site=		http://www.nongnu.org/libntlm/
Source=		http://www.nongnu.org/libntlm/releases//$(Name)-$(Version).tar.gz
License=	LGPL

define test_inner_hook
cat $(LibDir)/libntlm.la | grep libntlm
endef
