include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/PythonFormula.mk

Title=		libxml2-python
Name=		libxml2-python
Version=	2.6.21
Revision=	1
URL=		ftp://xmlsoft.org/libxml2/python/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/PKG-INFO
