include ../../Library/GNU.mk

Title=		Arp Scan
Name=		arp-scan
Version=	1.8
Revision=	0
URL=		http://www.nta-monitor.com/files/arp-scan
Source=		$(Name)-$(Version).tar.gz

define test_inner_hook
$(BinDir)/arp-scan --version
endef
