# requires Python Genshi >= 0.6

include ../../Library/Python.mk

Title=		Trac
Name=		trac
Version=	1.0.1
Revision=	0
URL=		http://download.edgewall.org/trac/
Source=		Trac-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
