BuildRequires += $(LibDir)/libjpeg.la

include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		Little CMS
Name=		lcms
Version=	1.19
Revision=	1
URL=		http://prdownloads.sourceforge.net/lcms/
URL=		http://sourceforge.net/projects/lcms/files/lcms/$(Version)/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README.1st
LicenseFile=	$(SourceDir)/COPYING
