include ../../Library/GNU.mk

Title=		Serf (Library)
Name=		serf
Version=	1.2.0
Revision=	0
URL=		http://serf.googlecode.com/files/
Source=		$(Name)-$(Version).tar.bz2

LicenseFile=	$(SourceDir)/LICENSE
