include ../../Library/GNU.mk

Title=		Serf (Library)
Name=		serf
Version=	1.2.0
Site=		http://code.google.com/p/serf/
Source=		http://serf.googlecode.com/files//$(Name)-$(Version).tar.bz2
License=	Apache License

LicenseFile=	$(SourceDir)/LICENSE
