include ../../Library/Config.mk
RUDIX_UNIVERSAL=
ArchFlags=-arch i386
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		Gforh
Name=		gforth
Version=	0.7.0
Revision=	0
URL=		http://ftp.gnu.org/gnu/gforth/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
