--- GNUmakefile.orig	2011-02-18 21:47:14.000000000 -0200
+++ GNUmakefile	2011-02-18 21:48:26.000000000 -0200
@@ -40,6 +40,11 @@
 CFLAGS+= -Wundef -Wbad-function-cast -Winline -Wcast-align
 endif
 
+ifdef FUNIVERSAL
+CFLAGS+= -arch i386 -arch x86_64 -Os
+LDFLAGS+= -arch i386 -arch x86_64
+endif
+
 # This sort of sucks but gets rid of the stupid warning and should work on
 # most platforms...
 ifeq ($(shell (LC_ALL=C $(CC) -v 2>&1|awk '/gcc version 4|clang/') || true), )
--- GNUmakefile.orig	2011-02-18 21:58:23.000000000 -0200
+++ GNUmakefile	2011-02-18 21:57:57.000000000 -0200
@@ -59,8 +59,8 @@
 PREFIX?= /usr/local
 INSTALL?= install
 INSTALLDIR= $(INSTALL) -d
-INSTALLBIN= $(INSTALL) -m 555
-INSTALLMAN= $(INSTALL) -m 444
+INSTALLBIN= $(INSTALL) -m 755
+INSTALLMAN= $(INSTALL) -m 644
 
 SRCS= $(shell echo *.c|LC_ALL=C sed 's|osdep-[a-z0-9]*.c||g')
 include config.mk
@@ -86,7 +86,7 @@
 install:	all
 		$(INSTALLDIR) $(DESTDIR)$(PREFIX)/bin
 		$(INSTALLBIN) tmux $(DESTDIR)$(PREFIX)/bin/tmux
-		$(INSTALLDIR) $(DESTDIR)$(PREFIX)/man/man1
-		$(INSTALLMAN) tmux.1 $(DESTDIR)$(PREFIX)/man/man1/tmux.1
+		$(INSTALLDIR) $(DESTDIR)$(PREFIX)/share/man/man1
+		$(INSTALLMAN) tmux.1 $(DESTDIR)$(PREFIX)/share/man/man1/tmux.1
 
 -include .depend
