include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	Display bandwidth usage on an interface
Site=		http://www.ex-parrot.com/pdw/iftop/
License=	GPL
Title=		iftop
Name=		iftop
Version=	0.17
Revision=	0
URL=		http://www.ex-parrot.com/pdw/iftop/download
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING
