BuildRequires += $(BinDir)/scons

include ../../Library/Scons.mk

Title=		MongoDB
Name=		mongodb
Version=	2.6.0
Revision=	0
Site=		http://www.mongodb.org/
Source=		http://downloads.mongodb.org/src/$(Name)-src-r$(Version).tar.gz
License=	AGPL
LicenseFile=	$(SourceDir)/GNU-AGPL-3.0.txt

UncompressedName=$(Name)-src-r$(Version)
