BuildRequires += $(BinDir)/scons

include ../../Library/GNU.mk

Title=		MongoDB
Name=		mongodb
Version=	2.4.4
Revision=	0
URL=		http://downloads.mongodb.org/src
Source=		$(Name)-src-r$(Version).tar.gz
LicenseFile=	$(SourceDir)/GNU-AGPL-3.0.txt

UncompressedName=$(Name)-src-r$(Version)
