BuildRequires += $(BinDir)/scons

include ../../Library/Scons.mk

Title=		MongoDB
Name=		mongodb
Version=	2.6.0
Revision=	0
URL=		http://downloads.mongodb.org/src
Source=		$(Name)-src-r$(Version).tar.gz
LicenseFile=	$(SourceDir)/GNU-AGPL-3.0.txt

UncompressedName=$(Name)-src-r$(Version)
