# Requires keyring

include ../../Library/Python.mk

Title=		Mercurial Keyring Extension
Name=		mercurial_keyring
Version=	0.5.7
Site=		http://pypi.python.org/pypi/mercurial_keyring
Source=		http://pypi.python.org/packages/source/m/mercurial_keyring//$(Name)-$(Version).tar.gz
License=	GPL

ReadMeFile=	$(SourceDir)/README.txt
LicenseFile=	$(SourceDir)/LICENSE.txt
