# Requires keyring

include ../../Library/Python.mk

Title=		Mercurial Keyring Extension
Name=		mercurial_keyring
Version=	0.5.1
Revision=	0
URL=		http://pypi.python.org/packages/source/m/mercurial_keyring/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README.txt
LicenseFile=	$(SourceDir)/PKG-INFO
