include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	Unit test framework for C programs
Site=		http://check.sourceforge.net/
License=	LGPL
Title=		Check $(Version)
Name=		check
Version=	0.9.8
Revision=	1
URL=		http://prdownloads.sourceforge.net/check
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING.LESSER
