include ../../Library/GNU.mk

Title=		Check
Name=		check
Version=	0.11.0
Site=		https://libcheck.github.io/check/
Source=		https://github.com/libcheck/check/releases/download/$(Version)/$(Name)-$(Version).tar.gz
License=	LGPL

LicenseFile=	$(SourceDir)/COPYING.LESSER
