include ../../Library/GNU.mk

Title=		Check
Name=		check
Version=	0.9.13
Revision=	0
Site=		http://check.sourceforge.net/
Source=		http://downloads.sourceforge.net/check/$(Name)-$(Version).tar.gz
License=	LGPL

LicenseFile=	$(SourceDir)/COPYING.LESSER
