include ../../Library/GNU.mk

Title=		fribidi
Name=		fribidi
Version=	1.0.5
Site=		https://github.com/fribidi/fribidi
Source=		https://github.com/fribidi/fribidi/releases/download/v$(Version)/fribidi-$(Version).tar.bz2
License=        GPL

GnuConfigureExtra += --enable-static
GnuConfigureExtra += --disable-debug
GnuConfigureExtra += --disable-dependency-tracking
GnuConfigureExtra += --disable-silent-rules


