include ../../Library/GNU.mk

Title=		GNU Screen
Name=		screen
Version=	4.0.3
Revision=	0
URL=		http://ftp.gnu.org/gnu/screen/
Source=		$(Name)-$(Version).tar.gz

GnuConfigureExtra += --with-sys-screenrc=/usr/local/etc
GnuConfigureExtra += -enable-telnet
