include ../../Library/GNU.mk

Title=		GNU Screen
Name=		screen
Version=	4.2.1
Revision=	0
Site=		http://www.gnu.org/software/screen/
Source=		http://ftp.gnu.org/gnu/screen//$(Name)-$(Version).tar.gz
License=	GPL

GnuConfigureExtra += --with-sys-screenrc=/usr/local/etc
GnuConfigureExtra += -enable-telnet
