name: builder
on:
  workflow_dispatch:
    inputs:
      portName:
        description: 'Name of the port'
        required: true
        default: 'hello'
      macOS:
        description: 'macOS Version'
        required: true
        type: choice
        default: 'macos-12'
        options:
        - macos-12
        - macos-11

jobs:
  run:
    name: ${{ github.event.inputs.portName }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          cd Ports/${{ github.event.inputs.portName }}
          make pkg
      - name: Test package
        run: |
          cd Ports/${{ github.event.inputs.portName }}
          make test
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.portName }}
          path: Ports/${{ github.event.inputs.portName }}/*macos*.pkg
      - uses: actions/download-artifact@v3
        with: 
          name: ${{ github.event.inputs.portName }}
