# $Id$

include ../../Library/Rules.mk

# http://pdos.csail.mit.edu/~baford/vm/

TITLE=		Vx32 (VERSION)
NAME=		vx32
VERSION=	0.12
REVISION=	0
URL=		http://pdos.csail.mit.edu/~baford/vm/release/
SOURCE=		$(NAME)-$(VERSION).tar.bz2

