include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Site=           http://aspell.net/
License=        LGPL
Description=    GNU Aspell spell checker
Title=          GNU Aspell
Name=           aspell
Version=        0.60.6
Revision=       0
URL=            ftp://ftp.gnu.org/gnu/aspell/
Source=         $(Name)-$(Version).tar.gz

ReadMeFile=     $(BuildDir)/README
LicenseFile=    $(BuildDir)/COPYING
