include ../../Library/Config.mk
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Description=	LZMA utils - make usage of LZMA compression easy
Site=		http://tukaani.org/lzma/
License=	GPL
Name=		lzma
Version=	4.32.7
Revision=	3
URL=		http://tukaani.org/lzma/
Source=		$(Name)-$(Version).tar.gz

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(PortDir)/COPYING
