include ../../Library/GNU.mk

Title=		Expat XML Parser
Name=		expat
Version=	2.4.1
Site=		https://libexpat.github.io/
Source=		https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.gz
License=	MIT

ReadMeFile=	$(SourceDir)/README.md
