include ../../Library/GNU.mk

Title=		Expat XML Parser
Name=		expat
Version=	2.1.0
Site=		http://expat.sourceforge.net
Source=		http://downloads.sourceforge.net/expat/$(Name)-$(Version).tar.gz
License=	MIT
